name: Deploy to VPS Servers

on:
  push:
    branches:
      - chicken_road_fs_10

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        site:
          - goldbet.wiki
          - promogb.com
          - goldbet.website
          - goldbet.click
          - goldbetio.com
          - goldbet.sbs
          - goldbet.monster
          - goldbet.lol
          - goldbet.cam
          - goldbet.cfd
          - goldbet.cyou
          - goldbet.fun
          - goldcvr88.xyz
          - goldimh6b.xyz
          - golds3s22.xyz
          - goldv5s3w.xyz
          - goldxe892.xyz
        vps:
          [
            PRIMA,
            ORANGE,
            NJAL,
            FLOKINET_FI_ONE,
            FLOKINET_NL,
            FLOKINET_FI_TWO,
            ISHOSTING_NL,
            ISHOSTING_CH,
            ISHOSTING_SR,
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy ${{ matrix.site }} → ${{ matrix.vps }}
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets[format('FTP_HOST_{0}', matrix.vps)] }}
          username: ${{ secrets[format('FTP_USER_{0}', matrix.vps)] }}
          password: ${{ secrets[format('FTP_PASSWORD_{0}', matrix.vps)] }}
          local-dir: ./dist/
          server-dir: /www/${{ matrix.site }}/chicken-road/nodep/10/
