name: Deploy to VPS Servers

on:
  push:
    branches:
      - two-step-form-identity

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        site:
          - promogb.com
          - goldbet.wiki
          # - goldv2k8.xyz
          # - goldx7p3.xyz
          # - goldv5s3w.xyz
          # - golds3s22.xyz
          # - golds0h7.xyz
          # - golds0h7.com
          # - goldm2n4.xyz
          # - goldm2n4.com
          # - goldimh6b.xyz
          # - golde5q1.xyz
          # - golde5q1.com
          # - goldbetio.com
          # - goldcvr88.xyz
          # - goldbet.website
          # - goldbet.sbs
          # - goldbet.monster
          # - goldbet.lol
          # - goldbet.fun
          # - goldbet.cyou
          # - goldbet.click
          # - goldbet.cfd
          # - goldbet.cam
          # - goldm5r2.com
          # - goldq8n1.com
          # - goldv3k7.com
          # - goldc9t4.com
          # - goldy6p8.com
          # - golda2w5.com
          # - goldu7h3.com
          # - goldl4x9.com
        vps:
          [
            FLOKINET_FI_ONE,
            FLOKINET_NL,
            FLOKINET_FI_TWO,
            ISHOSTING_NL,
            ISHOSTING_CH,
            ISHOSTING_SR,
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy ${{ matrix.site }} → ${{ matrix.vps }}
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets[format('FTP_HOST_{0}', matrix.vps)] }}
          username: ${{ secrets[format('FTP_USER_{0}', matrix.vps)] }}
          password: ${{ secrets[format('FTP_PASSWORD_{0}', matrix.vps)] }}
          local-dir: ./dist/
          server-dir: /www/${{ matrix.site }}/two-step-form/identity/
